# Generated by Django 6.0.2 on 2026-03-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='כותרת')),
                ('author', models.CharField(max_length=100, verbose_name='מחבר')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור')),
                ('published_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='תאריך הוצאה')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='מספר עמודים')),
                ('cover_image', models.URLField(blank=True, null=True, verbose_name='תמונת כריכה')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='isbn')),
                ('date_added_to_db', models.DateTimeField(auto_now_add=True, verbose_name='תאריך הוספה למערכת')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='תאריך שינוי אחרון')),
            ],
            options={
                'verbose_name': 'ספר',
                'verbose_name_plural': 'ספרים',
                'ordering': ['-date_added_to_db', 'author'],
            },
        ),
    ]
