# Generated by Django 6.0.3 on 2026-03-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='isbn'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'isbn')},
        ),
    ]
