# Generated by Django 6.0.3 on 2026-03-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_isbn_alter_book_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image_file',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='book_images/', verbose_name='תמונת כריכה ידנית', width_field='image_width'),
        ),
    ]
