# Generated by Django 6.0.3 on 2026-03-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book_cover_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/', verbose_name='תמונת כריכה ידנית'),
        ),
    ]
