# Generated by Django 6.0.3 on 2026-03-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_book_cover_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_loaned',
            field=models.BooleanField(default=False, help_text='האם הספר כרגע מושאל למישהו', verbose_name='מושאל?'),
        ),
        migrations.AddField(
            model_name='book',
            name='person_loaned_to',
            field=models.CharField(blank=True, null=True, verbose_name='שם השואל'),
        ),
    ]
