# Generated by Django 6.0.3 on 2026-03-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_is_loaned_book_person_loaned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.CharField(blank=True, choices=[('A', 'סלון'), ('B', 'מסדרון')], null=True),
        ),
    ]
