# Generated by Django 6.0.3 on 2026-03-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_book_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.CharField(blank=True, choices=[('A', 'סלון'), ('B', 'מסדרון')], null=True, verbose_name='מיקום'),
        ),
    ]
