# Generated by Django 6.0.3 on 2026-03-31 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_book_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='מיקום')),
            ],
            options={
                'verbose_name': 'מיקום',
                'verbose_name_plural': 'מיקומים',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.location', verbose_name='מיקום'),
        ),
    ]
