# Generated by Django 6.0.3 on 2026-04-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_tag_book_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='line_in_library',
            field=models.IntegerField(blank=True, null=True, verbose_name='שורה בספרייה'),
        ),
        migrations.AddField(
            model_name='book',
            name='shelf_in_line',
            field=models.IntegerField(blank=True, null=True, verbose_name='כוורת בשורה'),
        ),
    ]
